#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 01 16:52:51 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_log2_time_synth -key {Post-Synthesis:sim_1:Timing:test_log2} -tclbatch test_log2.tcl -log simulate.log"
xsim test_log2_time_synth -key {Post-Synthesis:sim_1:Timing:test_log2} -tclbatch test_log2.tcl -log simulate.log

